== TEST (2019-04-04 16:34:43) 
-- CODE:
from math import*

n=float(input("Insira o numero de pessoas:"))

p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
t=p*100
print(round(t,2))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 5, in <module>
    p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
TypeError: 'int' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-04-04 16:34:45) 
-- CODE:
from math import*

n=float(input("Insira o numero de pessoas:"))

p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
t=p*100
print(round(t,2))
-- EXECUTION TIME:
0.139095
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1594/1806/main.py", line 5, in <module>
    p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-04-04 16:34:48) 
-- CODE:
from math import*

n=float(input("Insira o numero de pessoas:"))

p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
t=p*100
print(round(t,2))
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 5, in <module>
    p= 1- factorial(365)/factorial(365-n) * 1 (365**n)
TypeError: 'int' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-04-04 16:35:06) 
-- CODE:
from math import*

n=float(input("Insira o numero de pessoas:"))

p= 1- factorial(365)/factorial(365-n) * 1 /(365**n)
t=p*100
print(round(t,2))
-- EXECUTION TIME:
0.131442
-- TEST CASE 1:
---- input:
12
---- correct output:
16.7
---- user output:
16.7
-- TEST CASE 2:
---- input:
24
---- correct output:
53.83
---- user output:
53.83
-- TEST CASE 3:
---- input:
99
---- correct output:
100.0
---- user output:
100.0
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
