== SUBMITION (2019-05-15 21:18:30) 
-- CODE:
from math import*
x= eval(input("qual seu angulo? "))
k= int(input("qual seu termo geral? "))
t=0
s=0
while (t<k):
	s= s + ((x*(2*t +1)/factorial(2*t+1)))(-1)**t
	t=t+1
print(round(s,10))
-- EXECUTION TIME:
0.181586
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 3, in <module>
    k= int(input())
EOFError: EOF when reading a line

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 21:25:20) 
-- CODE:
qp= int(input("qual a quantidade inicial de pirarucus?"))
cp= int(input("qual o percentual de crescimento?"))
pt=0
m=0
while (qp>0) and (qp<8000):
	qp=qp+(cp/100)*qp
	pt=int(input("qual a quantidade de pirarucus retirados?"))
	qp=qp-pt
	m=m+1
if (qp<=0):
	print("ZERO")
elif (qp>8000):
	print("MAXIMO")
print(m)
-- EXECUTION TIME:
0.293849
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 2, in <module>
    cp= int(input("qual o percentual de crescimento?"))
EOFError: EOF when reading a line

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-15 21:25:21) 
-- CODE:
qp= int(input("qual a quantidade inicial de pirarucus?"))
cp= int(input("qual o percentual de crescimento?"))
pt=0
m=0
while (qp>0) and (qp<8000):
	qp=qp+(cp/100)*qp
	pt=int(input("qual a quantidade de pirarucus retirados?"))
	qp=qp-pt
	m=m+1
if (qp<=0):
	print("ZERO")
elif (qp>8000):
	print("MAXIMO")
print(m)
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 2, in <module>
    cp= int(input())
EOFError: EOF when reading a line
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 21:25:22) 
-- CODE:
qp= int(input("qual a quantidade inicial de pirarucus?"))
cp= int(input("qual o percentual de crescimento?"))
pt=0
m=0
while (qp>0) and (qp<8000):
	qp=qp+(cp/100)*qp
	pt=int(input("qual a quantidade de pirarucus retirados?"))
	qp=qp-pt
	m=m+1
if (qp<=0):
	print("ZERO")
elif (qp>8000):
	print("MAXIMO")
print(m)
-- EXECUTION TIME:
0.206728
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 2, in <module>
    cp= int(input())
EOFError: EOF when reading a line

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 21:57:59) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))
-- EXECUTION TIME:
0.147096
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 8, in <module>
    soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 21:58:11) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))
-- EXECUTION TIME:
0.185025
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 8, in <module>
    soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 22:03:16) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))

-- EXECUTION TIME:
0.130046
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 8, in <module>
    soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 22:03:16) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))

-- EXECUTION TIME:
0.219493
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2508/main.py", line 8, in <module>
    soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-15 22:03:16) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))

-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 8, in <module>
    soma = soma + ((-1)*j)(4/(i*(i + 1)*(i + 2)))
TypeError: 'int' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 22:35:50) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)**j)*(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n -1
print(round(soma,8))

-- EXECUTION TIME:
0.135658
-- TEST CASE 1:
---- input:
5
---- correct output:
3.13968254
---- user output:
3.13968254
-- TEST CASE 2:
---- input:
22
---- correct output:
3.14161607
---- user output:
3.14161607
-- TEST CASE 3:
---- input:
19
---- correct output:
3.14155633
---- user output:
sigite os n primeiros termos: 3.14155633
-- GRADE:
67%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-15 22:36:00) 
-- CODE:
from math import*
n = int(input("sigite os n primeiros termos: "))

soma = 3
i = 2
j = 0
while(1<n):
	soma = soma + ((-1)**j)*(4/(i*(i + 1)*(i + 2)))
	i = i + 2
	j = j + 1
	n = n - 1
print(round(soma,8))

-- EXECUTION TIME:
0.136115
-- TEST CASE 1:
---- input:
5
---- correct output:
3.13968254
---- user output:
3.13968254
-- TEST CASE 2:
---- input:
22
---- correct output:
3.14161607
---- user output:
3.14161607
-- TEST CASE 3:
---- input:
19
---- correct output:
3.14155633
---- user output:
3.14155633
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
