== TEST (2019-03-12 17:48:14) 
-- CODE:
print(50//3)(50%3)
-- ERROR:
Traceback (most recent call last):
  File "XXXX", line 1, in <module>
    print(50//3)(50%3)
TypeError: 'NoneType' object is not callable
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-12 17:48:25) 
-- CODE:
print(50//3)(50%3)
-- EXECUTION TIME:
0.156478
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1582/1331/main.py", line 1, in <module>
    print(50//3)(50%3)
TypeError: 'NoneType' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-03-12 17:49:26) 
-- CODE:
print(50//3)
print(50%3)
-- OUTPUT:
16
2
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-12 17:49:30) 
-- CODE:
print(50//3)
print(50%3)
-- EXECUTION TIME:
0.125118
-- TEST CASE 1:
---- input:
xx
---- correct output:
16
2
---- user output:
16
2
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
