== SUBMITION (2019-03-11 15:29:58) 
-- CODE:
aresta =5
area = 3/2(3)**0.5*5**2
 
print(round(area, 4))
-- EXECUTION TIME:
0.223049
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1332/main.py", line 2, in <module>
    area = 3/2(3)**0.5*5**2
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:30:36) 
-- CODE:
aresta =5
area = 3/2(3)**0.5*5 ** 2
 
print(round(area, 4))
-- EXECUTION TIME:
0.136123
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1573/1332/main.py", line 2, in <module>
    area = 3/2(3)**0.5*5 ** 2
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-03-11 15:30:56) 
-- CODE:
aresta =5
area = 3/2*(3)**0.5*5 ** 2
 
print(round(area, 4))
-- EXECUTION TIME:
0.157713
-- TEST CASE 1:
---- input:
xxx
---- correct output:
64.9519
---- user output:
64.9519
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
