== SUBMITION (2019-05-14 11:09:06) 
-- CODE:
n = int(input("n: "))

soma = 0
i = 0
fim = n - 1

while(i<=fim):
	soma = soma ((-1)**i)*(4/(2*i+1))
	i = i + 1

print(round(soma, 8))
-- EXECUTION TIME:
0.190307
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1723/2503/main.py", line 8, in <module>
    soma = soma ((-1)**i)*(4/(2*i+1))
TypeError: 'int' object is not callable

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-14 11:09:13) 
-- CODE:
n = int(input("n: "))

soma = 0
i = 0
fim = n - 1

while(i<=fim):
	soma = soma + ((-1)**i)*(4/(2*i+1))
	i = i + 1

print(round(soma, 8))
-- EXECUTION TIME:
0.151271
-- TEST CASE 1:
---- input:
136
---- correct output:
3.13423981
---- user output:
3.13423981
-- TEST CASE 2:
---- input:
22
---- correct output:
3.09616153
---- user output:
3.09616153
-- TEST CASE 3:
---- input:
15
---- correct output:
3.20818565
---- user output:
3.20818565
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
