== SUBMITION (2019-05-08 14:29:44) 
-- CODE:
a= int(input("digite um número: "))
b=0
while(a!=-1):
	b = b + a
	a = int(input("digite um número: "))
print(b)
	
-- EXECUTION TIME:
0.19996
-- ERROR:
Traceback (most recent call last):
  File "/home/codebench/codes/1712/2496/main.py", line 1, in <module>
    a= int(input("digite um n\xfamero: "))
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 11: ordinal not in range(128)

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== TEST (2019-05-08 14:29:45) 
-- CODE:
a= int(input("digite um número: "))
b=0
while(a!=-1):
	b = b + a
	a = int(input("digite um número: "))
print(b)
	
-- OUTPUT:
874
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
== SUBMITION (2019-05-08 14:29:56) 
-- CODE:
a= int(input("digite um numero: "))
b=0
while(a!=-1):
	b = b + a
	a = int(input("digite um numero: "))
print(b)
	
-- EXECUTION TIME:
0.20915
-- TEST CASE 1:
---- input:
-525
1075
333
-9
-1

---- correct output:
874
---- user output:
874
-- TEST CASE 2:
---- input:
0
0
0
0
0
0
0
-1
---- correct output:
0
---- user output:
0
-- TEST CASE 3:
---- input:
10953
32653
-10953
-1
---- correct output:
32653
---- user output:
32653
-- GRADE:
100%
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
